---
# Defaults for roles/common
common_system_packages:
  - curl
  - wget
  - git
  - tar
  - rsync
  - firewalld
  - htop

# Default hardening settings (can be overridden in group_vars)
common_ssh_port: 22
common_ssh_permit_root_login: "no"
common_ssh_password_authentication: "no"

common_sysctl_settings:
  - { name: "net.ipv4.ip_forward", value: "0" }
  - { name: "net.ipv4.conf.all.accept_source_route", value: "0" }
  - { name: "net.ipv4.conf.all.accept_redirects", value: "0" }
