---
all:
  hosts:
    staging-bastion.local:
      ansible_host: 172.16.10.5
      ansible_user: admin
  children:
    webservers:
      hosts:
        staging-web-01.local:
          ansible_host: 172.16.10.11
        staging-web-02.local:
          ansible_host: 172.16.10.12
    databases:
      hosts:
        staging-db-01.local:
          ansible_host: 172.16.10.21
    loadbalancers:
      hosts:
        staging-lb-01.local:
          ansible_host: 172.16.10.31
