---
all:
  hosts:
    prod-bastion.local:
      ansible_host: 10.0.10.5
      ansible_user: admin
  children:
    webservers:
      hosts:
        prod-web-01.local:
          ansible_host: 10.0.10.11
        prod-web-02.local:
          ansible_host: 10.0.10.12
    databases:
      hosts:
        prod-db-01.local:
          ansible_host: 10.0.10.21
    loadbalancers:
      hosts:
        prod-lb-01.local:
          ansible_host: 10.0.10.31
